stages:
  - build

variables:
  imageversion: "latest"
  pushtag: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${imageversion}"

#
# -> Templates
#

.tpl:docker:
  image: docker:stable
  before_script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}"
  after_script:
    - "docker logout ${CI_REGISTRY}"
    - "docker image prune -f"
  tags:
    - docker
  except:
    changes:
      - "*.md"

#
# -> Jobs
#

build:
  extends: .tpl:docker
  stage: build
  script:
    - 'docker build -t "${pushtag}" .'
    - 'docker push "${pushtag}"'
